/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import java.util.Date;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfAWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.Font;
import java.io.FileOutputStream;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import com.itextpdf.text.Document;
import javax.swing.JTabbedPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author PaPa
 */
public class Software extends javax.swing.JPanel {
 JTabbedPane jt=null;
  Connection conn =null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    TableRowSorter<TableModel> sorter =null;
    /**
     * Creates new form Software
     */
    public Software(JTabbedPane jtp) {
        initComponents();
        jt= jtp;
        conn=JavaConnect.ConnecrDb();
        Update_table();
        
        
    }
     private void Update_table(){
        try{
        
            String sql ="select * from SoftwareDB";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            TableModel tm = DbUtils.resultSetToTableModel(rs);
            software_table.setModel(tm);
            sorter = new TableRowSorter<TableModel>(tm);
            software_table.setRowSorter(sorter);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }finally{
            try{
            rs.close();
            pst.close();
            }
            catch(Exception e){
            }
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        software_table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_softid = new javax.swing.JTextField();
        txt_softname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        cmd_report = new javax.swing.JButton();
        cmd_print1 = new javax.swing.JButton();

        setName("Software Info");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Command", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Software Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        software_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        software_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                software_tableMouseClicked(evt);
            }
        });
        software_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                software_tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(software_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 0), new java.awt.Color(153, 255, 153), null, null));

        jLabel2.setText("Software -name");

        jLabel1.setText("Software-ID");

        jLabel4.setText("Remark");

        jLabel3.setText("Description");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_softid, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(txt_description)
                    .addComponent(txt_remark)
                    .addComponent(txt_softname))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_softid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_softname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        cmd_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/report-icon.png"))); // NOI18N
        cmd_report.setText("Report");
        cmd_report.setToolTipText("Reports.....");
        cmd_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_reportActionPerformed(evt);
            }
        });

        cmd_print1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/printer-icon.png"))); // NOI18N
        cmd_print1.setText("Print");
        cmd_print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_print1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmd_report)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_print1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd_report)
                            .addComponent(cmd_print1))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
        
        String value1=txt_softid.getText();
        String value2=txt_softname.getText();
 	
 	String value3=txt_description.getText();
 	
 	String value4=txt_remark.getText();
        
        String sql="update softwareDB set Software_name='"+value2+"',Description='"+value3+"',Remark='"+value4+"' where  SoftwareID='"+value1+"'";
        pst=conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Data is Updated");
            
        
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
            
            pst.close();
            }catch(Exception e){
        
            }
        }
        Update_table();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
            
            String sql = "Insert into SoftwareDB (SoftwareID,Software_name,Description,Remark) values (?,?,?,?)";
            
            pst=conn.prepareStatement(sql);
            
            pst.setString(1,txt_softid.getText());
            pst.setString(2,txt_softname.getText());
            pst.setString(3,txt_description.getText());
            pst.setString(4,txt_description.getText());
            
           
            
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "New Data is added");
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
            
            pst.close();
            }catch(Exception e){
        
            }
        }
        Update_table();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int p= JOptionPane.showConfirmDialog(null,"Do you really want to delete","Delete",JOptionPane.YES_NO_OPTION); 
         
         
         if(p==0){
        String sql="delete from SoftwareDB where SoftwareID =?";
        try{
          pst=conn.prepareStatement(sql);
            
            pst.setString(1,txt_softid.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data is deleted");
            
          }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
            
            pst.close();
            }catch(Exception e){
        
            }
        }
        Update_table();
        
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txt_softid.setText("");
        txt_softname.setText("");
        txt_description.setText("");
        txt_remark.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void software_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_software_tableMouseClicked
        try{
      
          int row = software_table.getSelectedRow();
          String Table_click=(software_table.getModel().getValueAt(row,0).toString());
          String sql="select * from SoftwareDB where SoftwareID='"+Table_click+"'";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
          while(rs.next()){
          
                 String add1=rs.getString("SoftwareID");
                txt_softid.setText(add1);
             
                
                
                
                String add3=rs.getString("Software_name");
                txt_softname.setText(add3);
                
                String add4=rs.getString("Remark");
                txt_remark.setText(add4);
              
                String add6=rs.getString("Description");
                txt_description.setText(add6);
               
               
          
          }
       
      
      }
      
      catch(Exception e){
      
       JOptionPane.showMessageDialog(null, e);
      
      }
        finally{
            try{
            rs.close();
            pst.close();
            }catch(Exception e){
        
             }
        }
      
    }//GEN-LAST:event_software_tableMouseClicked

    private void software_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_software_tableKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP ){
         try{
      
          int row = software_table.getSelectedRow();
          String Table_click=(software_table.getModel().getValueAt(row,0).toString());
          String sql="select * from SoftwareDB where SoftwareID='"+Table_click+"'";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
          while(rs.next()){
          
                 String add1=rs.getString("SoftwareID");
                txt_softid.setText(add1);
             
                
                
                
                String add3=rs.getString("Software_name");
                txt_softname.setText(add3);
                
                String add4=rs.getString("Remark");
                txt_remark.setText(add4);
              
                String add6=rs.getString("Description");
                txt_description.setText(add6);
               
               
          
          }
       
      
      }
      
      catch(Exception e){
      
       JOptionPane.showMessageDialog(null, e);
      
      }
        finally{
            try{
            rs.close();
            pst.close();
            }catch(Exception e){
        
             }
        }
      
        }
    }//GEN-LAST:event_software_tableKeyReleased

    private void cmd_print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_print1ActionPerformed
        MessageFormat header = new MessageFormat(" IUT Computer Center :: Software Information");
        
       

        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {

            software_table.print(JTable.PrintMode.NORMAL, header, footer);
            
        } catch (java.awt.print.PrinterException e) {
            System.err.format("can't print", e.getMessage());

        }
        JOptionPane.showMessageDialog(null, "Report Printed");        
        
    }//GEN-LAST:event_cmd_print1ActionPerformed
public String CurrentDate() {
         
        String date_time=null;
        Calendar cal = new GregorianCalendar();
        Integer month = cal.get(Calendar.MONTH);
        Integer year = cal.get(Calendar.YEAR);
        Integer day = cal.get(Calendar.DAY_OF_MONTH);
        
        Integer second = cal.get(Calendar.SECOND);
        Integer minute = cal.get(Calendar.MINUTE);
        Integer hour = cal.get(Calendar.HOUR);
        date_time=year.toString()+month.toString()+day.toString()+hour.toString()+minute.toString()+second.toString();
        return date_time;
    }
    private void cmd_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_reportActionPerformed
          try {

            
            Document doc = new Document();
            PdfAWriter.getInstance(doc, new FileOutputStream("Report"+CurrentDate()+".pdf"));
            doc.open();
            doc.add(new Paragraph("IUT Computer Center :: Software Information", FontFactory.getFont(FontFactory.TIMES_BOLD, 
18, Font.BOLD, BaseColor.GRAY)));
            doc.add(new Paragraph(new java.util.Date().toString()));
            doc.add(new Paragraph("             "));

            int col = software_table.getColumnCount()-1;
            PdfPTable table = new PdfPTable(col);

            for (int i = 0; i < col; i++) {
                String col_name = software_table.getColumnName(i);
                table.addCell(new Paragraph(col_name, FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, 
BaseColor.BLUE)));
            }
            int row = software_table.getRowCount();

            for (int i = 0; i < row; i++) {
                for(int j=0;j<col;j++){
                String temp = (software_table.getModel().getValueAt(i,j).toString());
                table.addCell(temp);
                }
            }


           doc.add(table);
           doc.close();
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        JOptionPane.showMessageDialog(null, "Report Printed");



  


    }//GEN-LAST:event_cmd_reportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_print1;
    private javax.swing.JButton cmd_report;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable software_table;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_remark;
    private javax.swing.JTextField txt_softid;
    private javax.swing.JTextField txt_softname;
    // End of variables declaration//GEN-END:variables
}
